/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedCajaRouteImport } from './routes/_authenticated/caja'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedFotocopiasRouteImport } from './routes/_authenticated/fotocopias'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedProductosRouteImport } from './routes/_authenticated/productos'
import { Route as AuthenticatedProveedoresRouteImport } from './routes/_authenticated/proveedores'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'
import { Route as AuthenticatedReposicionRouteImport } from './routes/_authenticated/reposicion'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedVentaRouteImport } from './routes/_authenticated/venta'
import { Route as AuthenticatedVentasRouteImport } from './routes/_authenticated/ventas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCajaRoute = AuthenticatedCajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFotocopiasRoute = AuthenticatedFotocopiasRouteImport.update({
  id: '/fotocopias',
  path: '/fotocopias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductosRoute = AuthenticatedProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProveedoresRoute =
  AuthenticatedProveedoresRouteImport.update({
    id: '/proveedores',
    path: '/proveedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReposicionRoute = AuthenticatedReposicionRouteImport.update({
  id: '/reposicion',
  path: '/reposicion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVentaRoute = AuthenticatedVentaRouteImport.update({
  id: '/venta',
  path: '/venta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVentasRoute = AuthenticatedVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/caja': typeof AuthenticatedCajaRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/fotocopias': typeof AuthenticatedFotocopiasRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/productos': typeof AuthenticatedProductosRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/reposicion': typeof AuthenticatedReposicionRoute
  '/stock': typeof AuthenticatedStockRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/venta': typeof AuthenticatedVentaRoute
  '/ventas': typeof AuthenticatedVentasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/caja': typeof AuthenticatedCajaRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/fotocopias': typeof AuthenticatedFotocopiasRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/productos': typeof AuthenticatedProductosRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/reposicion': typeof AuthenticatedReposicionRoute
  '/stock': typeof AuthenticatedStockRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/venta': typeof AuthenticatedVentaRoute
  '/ventas': typeof AuthenticatedVentasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/caja': typeof AuthenticatedCajaRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/fotocopias': typeof AuthenticatedFotocopiasRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/productos': typeof AuthenticatedProductosRoute
  '/_authenticated/proveedores': typeof AuthenticatedProveedoresRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/_authenticated/reposicion': typeof AuthenticatedReposicionRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/venta': typeof AuthenticatedVentaRoute
  '/_authenticated/ventas': typeof AuthenticatedVentasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auditoria'
    | '/caja'
    | '/compras'
    | '/fotocopias'
    | '/panel'
    | '/productos'
    | '/proveedores'
    | '/reportes'
    | '/reposicion'
    | '/stock'
    | '/usuarios'
    | '/venta'
    | '/ventas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auditoria'
    | '/caja'
    | '/compras'
    | '/fotocopias'
    | '/panel'
    | '/productos'
    | '/proveedores'
    | '/reportes'
    | '/reposicion'
    | '/stock'
    | '/usuarios'
    | '/venta'
    | '/ventas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/auditoria'
    | '/_authenticated/caja'
    | '/_authenticated/compras'
    | '/_authenticated/fotocopias'
    | '/_authenticated/panel'
    | '/_authenticated/productos'
    | '/_authenticated/proveedores'
    | '/_authenticated/reportes'
    | '/_authenticated/reposicion'
    | '/_authenticated/stock'
    | '/_authenticated/usuarios'
    | '/_authenticated/venta'
    | '/_authenticated/ventas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caja': {
      id: '/_authenticated/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof AuthenticatedCajaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fotocopias': {
      id: '/_authenticated/fotocopias'
      path: '/fotocopias'
      fullPath: '/fotocopias'
      preLoaderRoute: typeof AuthenticatedFotocopiasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/productos': {
      id: '/_authenticated/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof AuthenticatedProductosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proveedores': {
      id: '/_authenticated/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof AuthenticatedProveedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reposicion': {
      id: '/_authenticated/reposicion'
      path: '/reposicion'
      fullPath: '/reposicion'
      preLoaderRoute: typeof AuthenticatedReposicionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/venta': {
      id: '/_authenticated/venta'
      path: '/venta'
      fullPath: '/venta'
      preLoaderRoute: typeof AuthenticatedVentaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventas': {
      id: '/_authenticated/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof AuthenticatedVentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedCajaRoute: typeof AuthenticatedCajaRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedFotocopiasRoute: typeof AuthenticatedFotocopiasRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedProductosRoute: typeof AuthenticatedProductosRoute
  AuthenticatedProveedoresRoute: typeof AuthenticatedProveedoresRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedReposicionRoute: typeof AuthenticatedReposicionRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVentaRoute: typeof AuthenticatedVentaRoute
  AuthenticatedVentasRoute: typeof AuthenticatedVentasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedCajaRoute: AuthenticatedCajaRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedFotocopiasRoute: AuthenticatedFotocopiasRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedProductosRoute: AuthenticatedProductosRoute,
  AuthenticatedProveedoresRoute: AuthenticatedProveedoresRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedReposicionRoute: AuthenticatedReposicionRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVentaRoute: AuthenticatedVentaRoute,
  AuthenticatedVentasRoute: AuthenticatedVentasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
